// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SpoolBuddy

#ifndef _SPOOLBUDDY_UI_H
#define _SPOOLBUDDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_HomeScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logos_spoolbuddy_logo_transparent_png);   // assets/logos/spoolbuddy_logo_transparent.png
LV_IMG_DECLARE( ui_img_icons_bell_light_png);   // assets/icons/bell_light.png
LV_IMG_DECLARE( ui_img_icons_cover_png);   // assets/icons/cover.png
LV_IMG_DECLARE( ui_img_icons_nfc_png);   // assets/icons/nfc.png
LV_IMG_DECLARE( ui_img_icons_scale_png);   // assets/icons/scale.png
LV_IMG_DECLARE( ui_img_icons_filament_png);   // assets/icons/filament.png
LV_IMG_DECLARE( ui_img_icons_rfid_png);   // assets/icons/rfid.png
LV_IMG_DECLARE( ui_img_icons_catalog_png);   // assets/icons/catalog.png
LV_IMG_DECLARE( ui_img_icons_settings2_png);   // assets/icons/settings2.png
LV_IMG_DECLARE( ui_img_icons_ams_png);   // assets/icons/ams.png
LV_IMG_DECLARE( ui_img_icons_dot_png);   // assets/icons/dot.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
