// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SpoolBuddy

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_StatusBar;
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_printerselect;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image15;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_center;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Image20;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Image26;
extern lv_obj_t *ui_Image27;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Image21;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Image22;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Image23;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Image24;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Image30;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Panel20;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Panel21;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_bottom;
extern lv_obj_t *ui_Image18;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

